// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0MZQMTm8_0sNh0H-6CnVCkPkIajH1gCQ',
    appId: '1:595467418671:web:2f76fdbfbb2b2f6aa2dada',
    messagingSenderId: '595467418671',
    projectId: 'gdg-event-be6d0',
    authDomain: 'gdg-event-be6d0.firebaseapp.com',
    storageBucket: 'gdg-event-be6d0.firebasestorage.app',
    measurementId: 'G-FY6BKSJ45R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINb8ryZZ9SlLW9dy-7-z7D883EdWy3jk',
    appId: '1:595467418671:android:188d07641cd47790a2dada',
    messagingSenderId: '595467418671',
    projectId: 'gdg-event-be6d0',
    storageBucket: 'gdg-event-be6d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgHm80L4Cw41-FX8PTCUqcUeOytnV9ANI',
    appId: '1:595467418671:ios:63b59123ac0a20aca2dada',
    messagingSenderId: '595467418671',
    projectId: 'gdg-event-be6d0',
    storageBucket: 'gdg-event-be6d0.firebasestorage.app',
    iosBundleId: 'com.example.gddg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgHm80L4Cw41-FX8PTCUqcUeOytnV9ANI',
    appId: '1:595467418671:ios:63b59123ac0a20aca2dada',
    messagingSenderId: '595467418671',
    projectId: 'gdg-event-be6d0',
    storageBucket: 'gdg-event-be6d0.firebasestorage.app',
    iosBundleId: 'com.example.gddg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0MZQMTm8_0sNh0H-6CnVCkPkIajH1gCQ',
    appId: '1:595467418671:web:a003d8704a65ed49a2dada',
    messagingSenderId: '595467418671',
    projectId: 'gdg-event-be6d0',
    authDomain: 'gdg-event-be6d0.firebaseapp.com',
    storageBucket: 'gdg-event-be6d0.firebasestorage.app',
    measurementId: 'G-6003RM9Y00',
  );
}
